### ISSUE TITLE
Issue with named instances

### ISSUE THREAD

**Issue by demyte** [ctrlbold/dbatools#30]
Hi,

I am having issues with running migrations on from/to named instances.

For example, if I run:

Copy-SqlLinkedServer -Source server\instance -Destination server\instance2

I get the following error:
WARNING: <Name> could not be added to server\instance
WARNING: Reason: System.Management.Automation.RuntimeException: The regular expression pattern 'server\instance' is not valid. ---> System.ArgumentException: parsing "'server\instance'" - Unrecognized escape sequence \i.
   at System.Text.RegularExpressions.RegexParser.ScanCharEscape()
   at System.Text.RegularExpressions.RegexParser.ScanBasicBackslash()
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
   at System.Management.Automation.ParserOps.NewRegex(String patternString, RegexOptions options)
   at System.Management.Automation.ParserOps.ReplaceOperator(ExecutionContext context, IScriptExtent errorPosition, Object lval, Object rval, Boolean ignoreCase)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )

**Comment by ctrlbold** [comment]
Hey @demyte,
Thanks for reporting an issue. This issue was addressed in a previous version. Please update to the latest one and let me know if you continue to have issues.

**Comment by demyte** [comment]
I updated today using the "Invoke-Expression (Invoke-WebRequest https://git.io/vn1hQ)" method which from what I can see replaces all the old files.

Is that the correct method?

**Comment by demyte** [comment]
Hi @ctrlbold 

I think it must have had the files loaded in a session somewhere, I updated and then closed down all my sessions ISE/Prompts etc and it is now working.

Thanks for the quick response :)
